abstract final class AppDisclaimers {
  static const thirdPartyApiNotice =
      'Experts is not affiliated with, endorsed by, or sponsored by Finnhub, Twelve Data, or Google Gemini. Experts uses their APIs to provide market data and educational AI analysis.';

  static const marketDataApiNotice =
      'Experts uses Finnhub and Twelve Data APIs for market information and is not affiliated with either provider.';

  static const reportNotice =
      'Experts does not provide financial advice, trading recommendations, or guarantees of future performance. Experts is not affiliated with Finnhub, Twelve Data, or Google Gemini and uses third-party APIs for information and educational analysis.';

  static const aiAnalysisDisclaimerNotice =
      'Experts analyst perspectives are generated by AI, not by human financial experts. Forecasts and summaries can be incomplete, inaccurate, delayed, or miss important risks. Use them as educational context only, not as financial advice, trading recommendations, or guarantees.';

  static const aiConsentNotice =
      'Experts uses Google Gemini to generate educational market analysis. The app may send the selected ticker, market data, news summaries, your optional note, and uploaded chart images. Your name is not sent. Data is processed by Google Gemini, and you can revoke consent in Settings. Experts is not affiliated with Google Gemini and uses its API for educational AI analysis.';

  static const aiChatConsentNotice =
      'Enable AI data consent to send chat questions to Google Gemini. Experts is not affiliated with Google Gemini and uses its API for educational AI analysis.';
}
